source 'https://cdn.cocoapods.org/'
source 'https://bitbucket.org/meetingdoctors-team/cocoapods-specs.git'
platform :ios, '13.0'
use_frameworks!

def shared_pods
    pod 'MeetingDoctorsSDK', '5.5.1'
end

target 'MDExampleSwiftUI' do
  shared_pods

  target 'MDExampleSwiftUITests' do
    inherit! :search_paths
  end

  target 'MDExampleSwiftUIUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf' # avoid too many symbols
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = "YES"
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
 	current_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if current_target.nil? || Gem::Version.new(current_target) < Gem::Version.new('13.0')
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end