source 'https://cdn.cocoapods.org/'
source 'https://bitbucket.org/meetingdoctors-team/cocoapods-specs.git'
platform :ios, '13.0'
use_frameworks! 

def shared_pods
    pod 'MDChatSDK', '1.0.1-carrefour.1'
end

def firebase_pods
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Installations'
end

target 'Mediquo Swift Example App' do
  shared_pods
  firebase_pods

  target 'Mediquo Swift Example AppTests' do
    inherit! :search_paths
  end

  target 'Mediquo Swift Example AppUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
      if target.name != 'Mediquo Swift Example App'
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end