source 'https://cdn.cocoapods.org/'
source 'https://bitbucket.org/meetingdoctors-team/cocoapods-specs.git'

platform :ios, '11.0'
use_frameworks!

def shared_pods
    pod 'MeetingDoctorsSDK', '~> 5.0.0'
end

def firebase_pods
    pod 'Firebase/Crashlytics'
    pod 'Firebase/Analytics'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
    pod 'Firebase/Installations'
end

target 'MDSwiftExampleApp' do
  shared_pods
  firebase_pods

  target 'MDSwiftExampleAppTests' do
    inherit! :search_paths
  end

  target 'MDSwiftExampleAppUITests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf' # avoid too many symbols
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = "YES"
      config.build_settings['CODE_SIGN_IDENTITY'] = ''
    end
  end
end